apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservices
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: NodePort  # Change to LoadBalancer if on cloud
